- name: Install Oracle Instant Client
  hosts: oracle_benchmark_client_vms
  become: yes
  vars:
    tmp_dir: "/tmp"
    basic_rpm: "oracle-instantclient{{ oracle_major_version }}-basic-{{ oracle_major_version }}.{{ oracle_minor_version }}.x86_64.rpm"
    sqlplus_rpm: "oracle-instantclient{{ oracle_major_version }}-sqlplus-{{ oracle_major_version }}.{{ oracle_minor_version }}.x86_64.rpm"
    oracle_home_path: "/usr/lib/oracle/{{ oracle_major_version }}/client64"

  tasks:
    - name: Check if Oracle Instant Client is already installed
      stat:
        path: "{{ oracle_home_path }}"
      register: oracle_home

    - name: Set fact if installation is needed
      set_fact:
        install_required: "{{ not oracle_home.stat.exists }}"

    - name: Download Basic RPM
      get_url:
        url: "{{ base_url }}/{{ basic_rpm }}"
        dest: "{{ tmp_dir }}/{{ basic_rpm }}"
        mode: '0644'
      when: install_required

    - name: Download SQLPlus RPM
      get_url:
        url: "{{ base_url }}/{{ sqlplus_rpm }}"
        dest: "{{ tmp_dir }}/{{ sqlplus_rpm }}"
        mode: '0644'
      when: install_required

    - name: Install Basic client RPM
      dnf:
        name: "{{ tmp_dir }}/{{ basic_rpm }}"
        state: present
        disable_gpg_check: yes
      when: install_required
      register: install_basic

    - name: Install SQLPlus RPM
      dnf:
        name: "{{ tmp_dir }}/{{ sqlplus_rpm }}"
        state: present
        disable_gpg_check: yes
      when: install_required
      register: install_sqlplus

    - name: Refresh oracle_home status after install
      stat:
        path: "{{ oracle_home_path }}"
      register: oracle_home_after

    - name: Show Oracle Instant Client installation status
      debug:
        msg: |
          {% if oracle_home_after.stat.exists and install_required %}
          ✅ Oracle Instant Client was successfully installed.
          Configure below environment variables:
          ORACLE_HOME={{ oracle_home_after.stat.path }}
          LD_LIBRARY_PATH={{ oracle_home_after.stat.path }}/lib
          {% elif oracle_home_after.stat.exists and not install_required %}
          ⚠️ Oracle Instant Client was already installed — no changes made.
          Configure below environment variables:
          ORACLE_HOME={{ oracle_home_after.stat.path }}
          LD_LIBRARY_PATH={{ oracle_home_after.stat.path }}/lib
          {% else %}
          ❌ Oracle Instant Client installation directory not found at {{ oracle_home_path }}.
          Something went wrong during the installation.
          {% endif %}



    - name: Create benchmark directory
      file:
        path: "{{ benchmark_base_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Create TNS directory
      file:
        path: "{{ tns_admin_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Set environment variables for Oracle client
      lineinfile:
        path: "{{ user_home_path }}/.bash_profile"
        line: "{{ item }}"
        create: yes
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
      loop:
        - "export ORACLE_HOME={{ oracle_home_path }}"
        - "export PATH=$PATH:$ORACLE_HOME/bin"
        - "export LD_LIBRARY_PATH=$ORACLE_HOME/lib:$LD_LIBRARY_PATH"
        - "export TNS_ADMIN={{ tns_admin_path }}"

    - name: Source the updated .bash_profile
      shell: "source {{ user_home_path }}/.bash_profile"
      args:
        executable: /bin/bash
      become_user: "{{ system_user }}"
