apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oracle-exporter-monitor
  namespace: openshift-monitoring
  labels:
    app: oracle-observability-exporter
spec:
  selector:
    matchLabels:
      app: oracle-observability-exporter
  namespaceSelector:
    matchNames:
      - oracle-monitoring
  endpoints:
    - port: oracle-metrics
      path: /metrics
      interval: 30s
