- name: Install and Setup HammerDB for Oracle Benchmark
  hosts: hammerdb_oracle_client_vms
  become: yes
  vars:
    hammerdb_path: "{{ hammerdb_install_path }}"
  tasks:
    - name: Install tcl using raw command
      raw: dnf install -y tcl
      when: ansible_os_family == "RedHat"
      args:
        warn: false  # Disables Ansible's warning about using raw

    - name: Check if HammerDB is already extracted
      stat:
        path: "{{ hammerdb_path }}"
      register: hammerdb_dir_stat

    - name: Download HammerDB if not already downloaded
      get_url:
        url: "https://github.com/TPC-Council/HammerDB/releases/download/v{{ hammerdb_version }}/HammerDB-{{ hammerdb_version }}-RHEL8.tar.gz"
        dest: "/tmp/HammerDB-{{ hammerdb_version }}.tar.gz"
      when: hammerdb_dir_stat.stat.exists == false

    - name: Create OCPV benchmark base directory
      file:
        path: "{{ benchmark_base_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Create HammerDB base directory
      file:
        path: "{{ hammerdb_base_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Ensure HammerDB target path exists
      file:
        path: "{{ hammerdb_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Extract HammerDB if not already extracted
      unarchive:
        src: "/tmp/HammerDB-{{ hammerdb_version }}.tar.gz"
        dest: "{{ hammerdb_path }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
      when: hammerdb_dir_stat.stat.exists == false

    - name: Create scripts base directory
      file:
        path: "{{ scripts_base_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Create HammerDB scripts directory
      file:
        path: "{{ scripts_base_path }}/hammerdb"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Copy HammerDB scripts to organized location
      copy:
        src: ../../scripts/hammerdb/
        dest: "{{ scripts_base_path }}/hammerdb/"
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Create HammerDB results directory within scripts
      file:
        path: "{{ scripts_base_path }}/hammerdb/results"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Create environment file template for HammerDB
      template:
        src: ../../templates/hammerdb.env.j2
        dest: "{{ scripts_base_path }}/hammerdb/.env"
        mode: '0644'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"