- name: Install and Setup HammerDB for Oracle Benchmark
  hosts: hammerdb_oracle_client_vms
  become: yes
  vars:
    hammerdb_path: "{{ hammerdb_base_path }}/{{ hammerdb_version }}"
  tasks:
    - name: Install tcl using raw command
      raw: dnf install -y tcl
      when: ansible_os_family == "RedHat"
      args:
        warn: false  # Disables Ansible's warning about using raw

    - name: Check if HammerDB is already extracted
      stat:
        path: "{{ hammerdb_path }}"
      register: hammerdb_dir_stat

    - name: Download HammerDB if not already downloaded
      get_url:
        url: "https://github.com/TPC-Council/HammerDB/releases/download/v{{ hammerdb_version }}/HammerDB-{{ hammerdb_version }}-RHEL8.tar.gz"
        dest: "/tmp/HammerDB-{{ hammerdb_version }}.tar.gz"
      when: hammerdb_dir_stat.stat.exists == false

    - name: Ensure HammerDB target path exists
      file:
        path: "{{ hammerdb_path }}"
        state: directory
        mode: '0755'

    - name: Extract HammerDB if not already extracted
      unarchive:
        src: "/tmp/HammerDB-{{ hammerdb_version }}.tar.gz"
        dest: "{{ hammerdb_path }}"
        remote_src: yes
        extra_opts: [--strip-components=1]
      when: hammerdb_dir_stat.stat.exists == false

    - name: Copy scripts directory to target vm's benchmark_scripts folder recursively
      copy:
          src: ../../scripts/
          dest: "{{ hammerdb_base_path }}/benchmark_scripts"
          mode: '0755'

    - name: Recursively change ownership and permissions so that scripts are executable.
      ansible.builtin.command: chown -R cloud-user:cloud-user {{ hammerdb_base_path }}/benchmark_scripts