- name: Configure Oracle Client tnsnames.ora
  hosts: hammerdb_oracle_client_vms
  become: yes
  tasks:
    - name: Ensure the {{ tns_admin_path }} directory exists
      file:
        path: "{{ tns_admin_path }}"
        state: directory
        mode: '0755'

    - name: Create tnsnames.ora file for Oracle client
      template:
        src: "../../templates/tnsnames.ora.j2"
        dest: "{{ tns_admin_path }}/tnsnames.ora"
        mode: '0644'
      vars:
        tns_entries: "{{ oracle_tns_entries }}"
