---
- name: Configure TNS Names for Oracle Connectivity
  hosts: oracle_benchmark_client_vms
  become: yes
  tasks:
    - name: Load common variables
      include_vars: ../../vars/common.yml
      
    - name: Create TNS Admin directory
      file:
        path: "{{ tns_admin_path }}"
        state: directory
        mode: '0755'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Generate tnsnames.ora from template
      template:
        src: ../../templates/tnsnames.ora.j2
        dest: "{{ tns_admin_path }}/tnsnames.ora"
        mode: '0644'
        owner: "{{ system_user }}"
        group: "{{ system_group }}"

    - name: Display TNS configuration summary
      debug:
        msg: |
          ✅ TNS configuration completed successfully!
          
          Configuration Details:
          - TNS Admin Path: {{ tns_admin_path }}
          - TNS Names File: {{ tns_admin_path }}/tnsnames.ora
          - Default TNS Entry: {{ default_tns_entry }}
          - Available TNS Entries: {{ oracle_tns_entries | map(attribute='tns_name') | join(', ') }}
          
          Environment Variables:
          - TNS_ADMIN={{ tns_admin_path }}
          
          Test Connection:
          sqlplus <username>/<password>@{{ default_tns_entry }}
